[parity]
chain = "demo-spec.json"
base_path = "parity0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "10.0.2.15"
[ui]
interface = "10.0.2.15"
port = 8180
[dapps]
interface = "10.0.2.15"
port = 8080
