[parity]
chain = "demo-spec.json"
base_path = "parity1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "10.0.2.15"
[ui]
interface = "10.0.2.15"
port = 8181
[dapps]
interface = "10.0.2.15"
port = 8081
[websockets]
port = 8457